### ISSUE TITLE
application/octet-stream or nothing is better for .bin

### ISSUE THREAD

**Issue by Rikkuru** [markov2/perl5-MIME-Types#10]
https://www.iana.org/assignments/media-types/application/gltf-buffer

list .bin in extensions, but some type for 3D models is not  a good choice for .bin extension
It can be anything, so it is better to use application/octet-stream or not return type at all for this extension in mimeTypeOf

**Comment by markov2** [comment]
I totally agree with you (again!)

> It can be anything, so it is better to use application/octet-stream

There is no extension listed in the IANA definition for octet-stream, but I think it's the best choice.
