### ISSUE TITLE
2.17 breaks Catalyst::Plugin::Static::Simple

### ISSUE THREAD

**Issue by vanstyn** [markov2/perl5-MIME-Types#2]
Now it seems that the 2.17 release breaks Catalyst::Plugin::Static::Simple for similar reasons as #1 -- the same types are no longer being returned:

```
t/04static.t ............. 1/9 
#   Failed test 'unknown extension as text/plain ok'
#   at t/04static.t line 34.
#          got: 'audio/atrac-advanced-lossless'
#     expected: 'text/plain'
# Looks like you failed 1 test of 9.
t/04static.t ............. Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by markov2** [comment]
* Henry Van Styn (notifications@github.com) [180127 01:52]:
> Now it seems that the 2.17 release breaks
> Catalyst::Plugin::Static::Simple for similar reasons as #1 -- the same
> types are no longer being returned:

This release saw a large growth in the number of extensions is understands.
And the data may have slightly changed... so I did expect some breakage.
``
> t/04static.t ............. 1/9 
> #   Failed test 'unknown extension as text/plain ok'
> #   at t/04static.t line 34.
> #          got: 'audio/atrac-advanced-lossless'
> #     expected: 'text/plain'
> # Looks like you failed 1 test of 9.
> t/04static.t ............. Dubious, test returned 1 (wstat 256, 0x100)
> ```

The name of the test already gives the answer:
   'unknown extension as text/plain ok'

It tries extension omg, which is now in use by someone.

There is already a bug-report in RT for it
    https://rt.cpan.org/Ticket/Display.html?id=124211
-- 
Thanks for reporting,

               MarkOv

------------------------------------------------------------------------
drs Mark A.C.J. Overmeer                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by vanstyn** [comment]
I just starting to trying to make a fix in Catalyst::Plugin::Static:Simple to use a different, still unknown extension, and now it seems that MIME::Types is returning empty string instead of text/plain for this case, so it seems there is still a MIME::Types bug. So, after implementing the proposed change, the failure now looks like this:

```
t/04static.t .............. 1/12 
#   Failed test 'unknown extension as text/plain ok'
#   at t/04static.t line 34.
#          got: ''
#     expected: 'text/plain'
# Looks like you failed 1 test of 12.
```

**Comment by markov2** [comment]
* Henry Van Styn (notifications@github.com) [180127 18:56]:
> I just starting to trying to make a fix in
> Catalyst::Plugin::Static:Simple to use a different, still unknown
> extension, and now it seems that MIME::Types is returning empty string
> instead of text/plain for this case, so it seems there is still a
> MIME::Types bug. So, after implementing the proposed change, the failure
> now looks like this:
> 
> ```
> t/04static.t .............. 1/12 
> #   Failed test 'unknown extension as text/plain ok'
> #   at t/04static.t line 34.
> #          got: ''
> #     expected: 'text/plain'
> # Looks like you failed 1 test of 12.
> ```

You are using the pre-0.10 functional interface. (before nov 2001)

  sub by_suffix($)
  {   my $filename = shift;
      $mime_types ||= MIME::Types->new;
      my $mime     = $mime_types->mimeTypeOf($filename);

      my @data     = defined $mime ? ($mime->type, $mime->encoding) : ('','');
      wantarray ? @data : \@data;
  }

  sub mimeTypeOf($)
  {   my ($self, $name) = @_;
      (my $ext = lc $name) =~ s/.*\.//;
      my $type = $typedb{EXTENSIONS}{$ext} or return;
      $self->type($type);
  }

by_suffix() has not been changed since 2001
mimeTypeOf() changed in 2013 with release 2.00

Not found then return ''

Please adapt your code to use the object interface, and expect undef
on 'not found'.
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
drs Mark A.C.J. Overmeer                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net
