### ISSUE TITLE
Use video/mp4 for extension mp4

### ISSUE THREAD

**Issue by Rikkuru** [markov2/perl5-MIME-Types#5]
mimeTypeOf('mp4') returns 'application/mp4'

But as I understand according to https://tools.ietf.org/html/rfc4337#section-3.4 'application/mp4' is only used "if the file contains neither visual nor audio presentations"

When we don't know the content of the file it is better to use 'video/mp4' "for all other files, including those that have MPEG-J, etc., in addition to video or audio streams"

**Comment by markov2** [comment]
I think you mean https://tools.ietf.org/html/rfc4337#section-2

The situation is quite unclear for mp4.  In general, creating an mime-type based on a extension is simply a guess.  But I do agree with you: video/mp4 is more generic.  I have created a new category of manual patches :-(
