### ISSUE TITLE
application/vnd.youtube.yt OBSOLETED in favor of video/vnd.youtube.yt

### ISSUE THREAD

**Issue by Rikkuru** [markov2/perl5-MIME-Types#6]
https://www.iana.org/assignments/media-types/application/vnd.youtube.yt

**Comment by markov2** [comment]
I think "OBSOLETED", which is rarely used (I checked), is a weird expression: it means "not usable".  However, in all kinds of applications have a memory; a type can never disappear.  "DEPRECATED" would fit much better.

When an extension has multiple alternatives for mime-types, the alphabetically first is taken.  You contributed a better alternative for mp4 in #5, and I will add this one as well.
