### ISSUE TITLE
3gp, 3gpp preference is "video/3gpp"

### ISSUE THREAD

**Issue by Rikkuru** [markov2/perl5-MIME-Types#7]
3GPP can use audio and video but video will be better when we don't know the content.
https://tools.ietf.org/html/rfc3839#section-3.2
```
The type "video/3gpp" is valid for all files.  It is valid to serve an audio-only file as "video/3gpp".
```

**Comment by markov2** [comment]
Are you going through all 2965 types?  Wow!

**Comment by Rikkuru** [comment]
no ) i had tests on this ones that broke after update

**Comment by markov2** [comment]
Sorry for the breakage.  Guessing mime-type based on file-name extension is a risky business.  You made it a little safer ;-)

**Comment by Rikkuru** [comment]
Thank you for quick response !
