### ISSUE TITLE
wrong extensions for image/heic and some others

### ISSUE THREAD

**Issue by Rikkuru** [markov2/perl5-MIME-Types#9]
I noticed some strange extensions and now I am pretty sure they were automatically parsed from rfc, but since it is not structured errors sometimes occur
## image/heic: subtype, for
```
subtype;image/heic
for;image/heic
```
I think this 2 extensions we parsed automatically from rfc 
https://www.iana.org/assignments/media-types/image/heic
```
   File extension(s): heif (for subtype heif), heic (for subtype 
      heic), hif (for subtypes heif and heic)
```
.for can be an extension for "text/x-fortran" according to sources/from-apache

## application/vnd.wfa.dpp: NA
Same for application/vnd.wfa.dpp
```
NA;application/vnd.wfa.dpp
```
https://www.iana.org/assignments/media-types/application/vnd.wfa.dpp
```
Additional information:

   1. Deprecated alias names for this type: NA
   2. Magic number(s): NA
   3. File extension(s): NA
```
## image/avif: or
image/avif does not have extension "or"
```
75:image:I:E
...
avif;avif,heif,heifs,or,hif;
```
https://www.iana.org/assignments/media-types/image/avif

## application/vnd.etsi.asic-e+zip: or
```
or;application/vnd.etsi.asic-e+zip
```
and in 
```
vnd.etsi.asic-e+zip;asice,or,sce;
vnd.etsi.asic-s+zip;asics,or,scs;
```
https://www.iana.org/assignments/media-types/application/vnd.etsi.asic-e+zip
```
2. File extension(s) : asice or sce
```
## vnd.exstream-package: or
```
vnd.exstream-package;pub,or,pkg;
```
https://www.iana.org/assignments/media-types/application/vnd.exstream-package
```
3. File extension(s): pub or pkg
```
## audio/atrac-advanced-lossless: and
```
and;audio/atrac-advanced-lossless
...
atrac-advanced-lossless;aal,aa3,and,omg;
atrac-x;atx,aa3,and,omg;
atrac3;at3,aa3,and,omg;
```
https://www.iana.org/assignments/media-types/audio/ATRAC-ADVANCED-LOSSLESS
```
File extension(s):  'aal', 'aa3', and 'omg'
```

# image/heif-sequence is better for .heifs
```
heifs;image/avif
```
As i got it avif is a subtype of heif - https://aomediacodec.github.io/av1-avif/
```
This document specifies syntax and semantics for the storage of [AV1] images in the generic image file format [HEIF], which is based on [ISOBMFF]. While [HEIF] defines general requirements, this document also specifies additional constraints to ensure higher interoperability between writers and readers when [HEIF] is used with [AV1] images.
```
So image/avif can have .heifs extension, but it is better to return image/heif-sequence type for .heifs

**Comment by markov2** [comment]
Prepared for the next release.  Thanks again!
